--------------------------------------------------------------------------
AVERAGE PAYMENT MADE BY EACH BUSINESS UNIT ON FY BASIS

SELECT AVG(PYMNT_AMT),BUSINESS_UNIT,FISCAL_YR_TAS FROM VENDOR_PAYMENTS
GROUP BY BUSINESS_UNIT,FISCAL_YR_TAS