---------------------------------------------------------------------------
PAYMENT MADE BY EACH BUSINESS UNIT ON MONTHLY BASIS

SELECT SUM(PYMNT_AMT),BUSINESS_UNIT, OCP_MONTH FROM VENDOR_PAYMENTS
GROUP BY BUSINESS_UNIT, OCP_MONTH