--------------------------------------------------------------------------
PAYMENT MADE BY EACH BUSINESS UNIT BASED ON FY BASIS

SELECT SUM(PYMNT_AMT), BUSINESS_UNIT, FISCAL_YR_TAS FROM VENDOR_PAYMENTS
GROUP BY BUSINESS_UNIT,FISCAL_YR_TAS;