---------------------------------------------------------------------------
PAYMENT MADE BY EACH BUSINESS UNIT VIA FUND_CODE

SELECT SUM(PYMNT_AMT), BUSINESS_UNIT, FUND_CODE FROM VENDOR_PAYMENTS
GROUP BY BUSINESS_UNIT, FUND_CODE;